#!/usr/bin/env python3
"""
scripts/publish_phoronix_pages.py -- materializes doc/REPORT_HIERARCHY.md's level-3 (test) and
level-4 (test-point) pages for Phoronix, on both the file-system report-root and the live WordPress
site. Same recipe as scripts/publish_cpu2026_benchmarks.py, adapted for two real differences: there
are far more Phoronix tests than cpu2026's fixed 52 benchmarks (so batch-creating *every possible*
Phoronix test would be wrong), and workload/phoronix/ already has materialized test/test-point data
committed to git as it was created -- that materialized set *is* the lazy list, no hand-curated data
file needed the way cpu2026's spec_benchmarks.json was.

Enumeration comes entirely from joblib.list_materialized_phoronix_test_points() -- no new data file:

  - Level 3, one per distinct materialized test (bare_name): content is the *existing*
    workload/phoronix/<test>/README.md write_phoronix_test_readme() already generates (description +
    detail fields sourced from `phoronix-test-suite info`, including an OpenBenchmarking.org Test
    Profile URL) -- copied into <report-root>/phoronix/<test>/README.md rather than generated fresh.
    doc/REPORT_HIERARCHY.md already flags this migration as outstanding debt; this closes it as a side
    effect. Rendered to WP via markdown_lite.to_wp_blocks() -- safe here (verified against all 97 real
    test READMEs during development, zero mangled-underscore cases) since this content uses plain
    bulleted URLs, never the `[text](url)` link syntax that broke on cpu2026's hand-authored content.

  - Level 4, one per (bare_name, options_slug) test-point that has at least one linked run -- NOT
    every materialized test-point. Of 443 materialized test-points across 97 tests, only 2 have ever
    actually been run; the rest are option combinations Phoronix's own suite-definition.xml expansion
    produced (e.g. 66 for llama-cpp alone), never benchmarked. Content (test point identity + its
    arguments) is new and hand-built as WP block markup, matching cpu2026's wp_content() pattern,
    since argument text is unpredictable (raw paths/flags/model filenames) and doesn't need
    markdown_lite's heading/list/bold support.

Deliberately manual, not wired into wspy-phoronix-import/materialize_phoronix_test_point() -- re-run
this whenever you want the hierarchy to catch up with newly materialized tests or newly-run test
points. Auto-triggering this from an import event is real future work, not started here.

Usage:
  publish_phoronix_pages.py --dry-run              # preview everything, touches nothing
  publish_phoronix_pages.py --test coremark         # just one test (+ its run test-points), for review
  publish_phoronix_pages.py                         # every materialized test, run test-points only
  publish_phoronix_pages.py --publish               # also flip each leaf page to published
"""
import argparse
import html
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
sys.path.insert(0, os.path.join(REPO_ROOT, "web"))
import joblib  # noqa: E402
import markdown_lite  # noqa: E402
import report_root  # noqa: E402
import wp_client  # noqa: E402
from wp_client import load_config  # noqa: E402

SUITE_SLUG = "phoronix"
SUITE_TITLE = "phoronix"
DEFAULT_PHORONIX_DEST_ROOT = os.path.join(REPO_ROOT, "workload", "phoronix")


def resolve_report_root(args):
    if args.report_root:
        return args.report_root
    cfg = load_config()
    if cfg and cfg.get("report_root"):
        return cfg["report_root"]
    return report_root.DEFAULT_REPORT_ROOT


def ensure_test_readme(report_root_path, phoronix_dest_root, bare_name, dry_run):
    """Additive -- copies workload/phoronix/<bare_name>/README.md (already generated by
    write_phoronix_test_readme()) into <report-root>/phoronix/<bare_name>/README.md only if the
    report-root copy doesn't already exist, so a human's later edits there survive a re-run. Returns
    (rel_path, content, created_bool), or (None, None, False) if no source README exists yet to copy
    (materialized without ever having phoronix-test-suite info fields available -- skip, don't fail)."""
    source_path = os.path.join(phoronix_dest_root, bare_name, "README.md")
    if not os.path.isfile(source_path):
        return None, None, False
    out_dir = os.path.join(report_root_path, SUITE_SLUG, bare_name)
    path = os.path.join(out_dir, "README.md")
    rel_path = os.path.relpath(path, report_root_path)
    if os.path.isfile(path):
        with open(path) as f:
            return rel_path, f.read(), False
    with open(source_path) as f:
        content = f.read()
    if not dry_run:
        os.makedirs(out_dir, exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
    return rel_path, content, True


def test_point_readme_content(entry):
    return (
        "# %s\n\n"
        "Test point identity: `%s`\n\n"
        "Arguments: `%s`\n"
        % (entry["identity"], entry["test_id"], entry["arguments"] or "(none)")
    )


def ensure_test_point_readme(report_root_path, entry, dry_run):
    """Additive, same convention as ensure_test_readme() -- new content this time (no existing
    file to copy), generated from the test-point's own materialized metadata."""
    out_dir = os.path.join(report_root_path, SUITE_SLUG, entry["bare_name"], entry["options_slug"])
    path = os.path.join(out_dir, "README.md")
    rel_path = os.path.relpath(path, report_root_path)
    if os.path.isfile(path):
        with open(path) as f:
            return rel_path, f.read(), False
    content = test_point_readme_content(entry)
    if not dry_run:
        os.makedirs(out_dir, exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
    return rel_path, content, True


def test_point_wp_content(entry):
    """Hand-built WP block markup, matching cpu2026's wp_content() pattern -- arguments text is
    unpredictable (raw paths/flags/model filenames) and doesn't need markdown_lite's heading/list/bold
    support, so there's no benefit to routing it through that module."""
    title = html.escape(entry["options_slug"])
    test_id = html.escape(entry["test_id"])
    arguments = html.escape(entry["arguments"] or "(none)")
    return (
        '<!-- wp:heading {"level":1} -->\n<h1>%s</h1>\n<!-- /wp:heading -->\n\n'
        '<!-- wp:paragraph -->\n<p>Test point identity: <code>%s</code></p>\n<!-- /wp:paragraph -->\n\n'
        '<!-- wp:paragraph -->\n<p>Arguments: <code>%s</code></p>\n<!-- /wp:paragraph -->'
        % (title, test_id, arguments)
    )


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--test", action="append", default=None,
                     help="restrict to this test's bare_name (repeatable); default: every materialized "
                          "test")
    ap.add_argument("--phoronix-dest-root", default=DEFAULT_PHORONIX_DEST_ROOT,
                     help="materialized Phoronix tree to read from (default: %s)"
                          % DEFAULT_PHORONIX_DEST_ROOT)
    ap.add_argument("--report-root", default=None, help="override the report-root path")
    ap.add_argument("--report-root-remote", default=report_root.DEFAULT_REPORT_ROOT_REMOTE,
                     help="report-root git remote, for clone-if-missing")
    ap.add_argument("--publish", action="store_true",
                     help="flip each WP page to status=publish (default: leave as draft)")
    ap.add_argument("--dry-run", action="store_true",
                     help="print what would be written/committed/published, touch nothing")
    args = ap.parse_args()

    all_points = joblib.list_materialized_phoronix_test_points(args.phoronix_dest_root)
    if not all_points:
        print("publish_phoronix_pages: no materialized test points under %s"
              % args.phoronix_dest_root, file=sys.stderr)
        return 1

    if args.test:
        wanted = set(args.test)
        all_points = [e for e in all_points if e["bare_name"] in wanted]
        missing = wanted - {e["bare_name"] for e in all_points}
        if missing:
            print("publish_phoronix_pages: unknown --test value(s): %s"
                  % ", ".join(sorted(missing)), file=sys.stderr)
            return 1

    tests = sorted({e["bare_name"] for e in all_points})
    run_points = sorted((e for e in all_points if e["runs"]), key=lambda e: e["identity"])

    report_root_path = resolve_report_root(args)
    if not args.dry_run:
        ok, msg = report_root.ensure_report_root(report_root_path, args.report_root_remote)
        print("publish_phoronix_pages: %s" % msg, file=sys.stderr)
        if not ok:
            return 1

    wp = None
    if not args.dry_run:
        cfg = load_config()
        wp = (cfg or {}).get("wordpress")
        if not wp:
            print("publish_phoronix_pages: no WordPress config -- run `wspy-publish configure` first",
                  file=sys.stderr)
            return 1

    # Phase 1: file-system README generation (both levels) + a single commit covering every new file.
    test_rows = []  # (bare_name, rel_path, content, created_bool) -- content may be None if skipped
    point_rows = []  # (entry, rel_path, content, created_bool)
    new_rel_paths = []
    new_names = []

    for bare_name in tests:
        rel_path, content, created = ensure_test_readme(
            report_root_path, args.phoronix_dest_root, bare_name, args.dry_run)
        if rel_path is None:
            print("  README %s: skipped (no workload/phoronix/%s/README.md to copy yet)"
                  % (bare_name, bare_name))
            continue
        test_rows.append((bare_name, rel_path, content, created))
        print("  README %s: %s" % (bare_name, "created" if created else "exists"))
        if created:
            new_rel_paths.append(rel_path)
            new_names.append(bare_name)

    for entry in run_points:
        rel_path, content, created = ensure_test_point_readme(report_root_path, entry, args.dry_run)
        point_rows.append((entry, rel_path, content, created))
        print("  README %s: %s" % (entry["identity"], "created" if created else "exists"))
        if created:
            new_rel_paths.append(rel_path)
            new_names.append(entry["identity"])

    if new_rel_paths:
        message = "Add Phoronix hierarchy README(s): %s" % ", ".join(new_names)
        if args.dry_run:
            print("publish_phoronix_pages: --dry-run -- would commit %d new README(s)"
                  % len(new_rel_paths), file=sys.stderr)
        else:
            ok, msg = report_root.commit_paths(report_root_path, new_rel_paths, message)
            print("publish_phoronix_pages: %s" % msg, file=sys.stderr)
            if not ok:
                return 1

    # Phase 2: WordPress draft pages -- level 3 first (test pages), then level 4 (run test-points)
    # nested under their now-guaranteed-to-exist test parent.
    failures = 0
    for bare_name, _, content, _ in test_rows:
        levels = [(SUITE_SLUG, SUITE_TITLE), (bare_name, bare_name)]
        blocks = markdown_lite.to_wp_blocks(content)
        if args.dry_run:
            print("  WP %s: would publish_page_at_path(levels=%r, content=%d bytes, publish=%s)"
                  % (bare_name, levels, len(blocks), args.publish))
            continue
        try:
            page, created = wp_client.publish_page_at_path(
                wp["site_url"], wp["username"], wp["app_password"], levels, blocks,
                do_publish=args.publish)
        except wp_client.WPError as e:
            print("  WP %s: FAILED (status=%s code=%s): %s" % (bare_name, e.status, e.code, e),
                  file=sys.stderr)
            failures += 1
            continue
        print("  WP %s: %s (id=%s, status=%s) link=%s"
              % (bare_name, "created" if created else "found/updated", page["id"],
                 page.get("status"), page.get("link")))

    for entry, _, _, _ in point_rows:
        levels = [(SUITE_SLUG, SUITE_TITLE), (entry["bare_name"], entry["bare_name"]),
                  (entry["options_slug"], entry["options_slug"])]
        blocks = test_point_wp_content(entry)
        if args.dry_run:
            print("  WP %s: would publish_page_at_path(levels=%r, content=%d bytes, publish=%s)"
                  % (entry["identity"], levels, len(blocks), args.publish))
            continue
        try:
            page, created = wp_client.publish_page_at_path(
                wp["site_url"], wp["username"], wp["app_password"], levels, blocks,
                do_publish=args.publish)
        except wp_client.WPError as e:
            print("  WP %s: FAILED (status=%s code=%s): %s" % (entry["identity"], e.status, e.code, e),
                  file=sys.stderr)
            failures += 1
            continue
        print("  WP %s: %s (id=%s, status=%s) link=%s"
              % (entry["identity"], "created" if created else "found/updated", page["id"],
                 page.get("status"), page.get("link")))

    if failures:
        print("publish_phoronix_pages: %d page(s) failed" % failures, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
